### ISSUE TITLE
[SPRING] Mandatory Views on custom screen

### ISSUE THREAD

**Issue by dpliskov** [SourcePointUSA/android-cmp-app#116]
We can create a layout sample_native_message.xml to use it as a custom consent screen without overriding NativeMessage methods. We can position view there in the way as we need. But we have to add all views on this screen even if we don't need them. 
For example i don't need the Reject All button. But i have to add view with id +id/RejectAll to my custom screen. Otherwise i get crash. 
Could you do these views nullable in your code?

**Comment by leodoin** [comment]
@dpliskov , the idea here is to aways create the mandatory views and wait for the messageAttributes object to tell you wether they should be visible or not. This way if you want to add a button on the future all you have to do is to include it on the message builder on our dashboard, not need for an app release!
I will explain on this ticket [https://github.com/SourcePointUSA/android-cmp-app/issues/129] how to get those attributes. But if it does not work for you we can plan on making then nullable for sure.

**Comment by dpliskov** [comment]
I still need to create stub views and hide them.

**Comment by leodoin** [comment]
@dpliskov , the views are now public and nullable. Do you still face the same issue or can we consider this as water under the bridge?

**Comment by atanurdemirci** [comment]
Fixed, Resolving!

**Comment by dpliskov** [comment]
@leodoin @atanurdemirci 
Checked on 5.3.6.
I still have to create the View with id rejectAll in my native screen layout. But i don't need it. 

Otherwise i get:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setVisibility(int)' on a null object reference
        at com.sourcepoint.gdpr_cmplibrary.NativeMessage.setRejectAll(NativeMessage.java:122)
        at com.sourcepoint.gdpr_cmplibrary.NativeMessage.init(NativeMessage.java:43)

**Comment by leodoin** [comment]
Fair enough @dpliskov , reopening the ticket and working on it right away!

**Comment by leodoin** [comment]
Hey @dpliskov , we prepared an [example branch](https://github.com/SourcePointUSA/android-cmp-app/pull/262) to show case how to instantiate the NativeMessage overloading the the right methods in a way that you don't have to add all action views to your layout, like it is done [here](https://github.com/SourcePointUSA/android-cmp-app/blob/e739bba5722532150921bfb46851af277f89f1fc/app/src/main/java/com/sourcepoint/example_app/MainActivity.java#L93) .
Pls keep in mind that you should not use or make any references to our own native_message_layout (it is just an example). Also it is recommended to have all views on your layout, so you can have the option the add some action on our dash board later with no need an app release 🧙
If you could give it a try and let us know if it works as expected to you or not we'd be glad to hear your feed back on that 😄

**Comment by dpliskov** [comment]
@leodoin 
Which version do you use for that sample? 
I tried with version 5.3.8.  If i don't call super.init() i get the error. It tries to set click listener for ActionButton that is null. 

com.sourcepoint.gdpr_cmplibrary.ConsentLibException: java.lang.NullPointerException: Attempt to read from field 'android.widget.Button com.sourcepoint.gdpr_cmplibrary.NativeMessage$ActionButton.button' on a null object reference
    at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.lambda$setNativeMessageView$2$GDPRConsentLib(GDPRConsentLib.java:251)
    at com.sourcepoint.gdpr_cmplibrary.-$$Lambda$GDPRConsentLib$z97h7nKc0UN6caY9AkUeCkdEb0E.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7037)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.Button com.sourcepoint.gdpr_cmplibrary.NativeMessage$ActionButton.button' on a null object reference
    at com.sourcepoint.gdpr_cmplibrary.NativeMessage.setOnclickAction(NativeMessage.java:51)
    at com.sourcepoint.gdpr_cmplibrary.NativeMessage.setCallBacks(NativeMessage.java:55)
    at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.lambda$setNativeMessageView$2$GDPRConsentLib(GDPRConsentLib.java:246)

**Comment by dpliskov** [comment]
@leodoin 
I got it. I need to override setCallBacks and make it empty, without calling super method. 
Now it works, thanks!
Close.
