### ISSUE TITLE
[SPRING] Cookie layer throws an error if Google Fonts request fails

### ISSUE THREAD

**Issue by anasonline** [SourcePointUSA/android-cmp-app#173]
In Bild Android app we use the [downloadable fonts](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts) feature to get the fonts used in the app. This makes a request to _fonts.googleapis.com_. 

We noticed a strange issue in which when the fonts request doesn't answer, then the SDK throws an "ApiException" that looks like:

`com.sourcepoint.gdpr_cmplibrary.ConsentLibException$ApiException
        at com.sourcepoint.gdpr_cmplibrary.ConsentWebView$1.onReceivedError(ConsentWebView.java:117)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410409683:133)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

with the error message: 
`Error due to android API: T7@340a516`

In our case, this causes the app to hang on the launch screen waiting infinitely for the Webview to be displayed.

**Comment by leodoin** [comment]
@anasonline , what do you mean by `the SDK throws an "ApiException"` ? Is the `onError` callback being called with this exception ? If so, this is actually the expected behaviour and you should use it to skip the loading state on your app implementation. Does it makes sense to you?

**Comment by andresilveirah** [comment]
@anasonline I'm closing this issue as I'm assuming the `onError` should capture this use case and you should be able to handle the error on your own. Let me know if that's not the case.
