### ISSUE TITLE
Cast wrong type in `ConsentLib.LoadTask`

### ISSUE THREAD

**Issue by julienbanse** [SourcePointUSA/android-cmp-app#18]
The result of `LoadTask` can forward an exception in listener that need a `String` object.

Here the stacktrace :
`Fatal Exception: java.lang.ClassCastException: java.io.FileNotFoundException cannot be cast to java.lang.String
       at com.example.cmplibrary.ConsentLib$4.onLoadCompleted(ConsentLib.java:914)
       at com.example.cmplibrary.ConsentLib$LoadTask.onPostExecute(ConsentLib.java:654)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(Unknown Source)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by andresilveirah** [comment]
@julienbanse I've released `cmplibrary` version 2.0 It's a big internal refactoring and it includes some breaking changes. Here's a [migration guide](https://github.com/SourcePointUSA/android-cmp-app/blob/master/CHANGELOG.md#migration-guide). If you have any questions or feedback, feel free to contact me directly on Slack or open another issue here.
