### ISSUE TITLE
[SPRING] pausing and resuming the app causes exception in SDK

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#185]
With Native Layer displayed on the screen, according to SourcePoint SDK settings, pausing and resuming the app (going to another app and back, or to homescreen and back) results in native layer no longer showing with following exception in the logs.

Additionally, this seems to result in a very strange and broken state in the app when even though native layer is not visible, it somehow still seems to be present in the hierarchy breaking the app functionality by messing with events and what can be displayed on the screen.

```
2020-06-25 16:08:43.816 16719-16719/de.cellular.n24hybrid.staging W/System.err: com.sourcepoint.gdpr_cmplibrary.ConsentLibException: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib$2.onSuccess(GDPRConsentLib.java:376)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.SourcePointClient$1.onResponse(SourcePointClient.java:84)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err: Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8648)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1533)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging I/chatty: uid=10411(de.cellular.n24hybrid.staging) identical 4 lines
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3172)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.requestLayout(View.java:24654)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.setFlags(View.java:15312)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at android.view.View.setVisibility(View.java:10919)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.NativeMessage.setChildAttributes(NativeMessage.java:85)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.NativeMessage.setAttributes(NativeMessage.java:62)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at de.weltn24.news.gdpr.GdprConsentNativeMessage.setAttributes(GdprConsentNativeMessage.kt:55)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.setNativeMessageView(GDPRConsentLib.java:246)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.access$000(GDPRConsentLib.java:24)
2020-06-25 16:08:43.817 16719-16719/de.cellular.n24hybrid.staging W/System.err:     at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib$2.onSuccess(GDPRConsentLib.java:367)
```

**Comment by AAverin** [comment]
Resolved in 5.2.6
