### ISSUE TITLE
[ANDROID] Incorrect error Msg, with no internet after clicking on Options

### ISSUE THREAD

**Issue by wezley98** [SourcePointUSA/android-cmp-app#195]
**The SDK is throwing the error callback which is correct but the error it returns need to be of type ConsentLibException.NoInternetConnectionException**

With the initial pop up, if you click on Options tab, with Airplane mode on, you get an error message (Sorry something went wrong trying to load this page(with a close button)

### Affected area’s
SourcePoint, Option tab

### Steps:
- Fresh install of the App
- follow user journey
- See SourcePoint Pop up
- Turn on AirPlane mode
- Click on Options Tab
- Here you are faced with  (Sorry something went wrong trying to load this page(with a close button)

### Expected Result:
Page should reflect that you have no internet, as it would when clicking accepts 

### Actual Result:
you are seeing (Sorry something went wrong trying to load this page(with a close button)

### Additional Details:
Same error message when clicking on partners with in the pop up too
Clicking on Accept with no wifi, you get the correct Message(It appears you don't have an internet connection Please Check and try again)With a retry button, When switching airplane mode off, SourcePoint Pop displays as expected

Devices:
|||:Device|:OS
|| Samsung Galaxy S7 edge|  8.0

**Comment by leodoin** [comment]
@wezley98 I think you might using a later version of the SDK. Could you confirm it?
On our example app from master I'm getting this no internet connection error instead:
```
2020-07-07 11:54:37.623 8402-8402/com.sourcepoint.example_app E/**MainActivity: Something went wrong: 
    com.sourcepoint.gdpr_cmplibrary.ConsentLibException: com.sourcepoint.gdpr_cmplibrary.ConsentLibException$NoInternetConnectionException
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.lambda$loadConsentUI$4$GDPRConsentLib(GDPRConsentLib.java:303)
        at com.sourcepoint.gdpr_cmplibrary.-$$Lambda$GDPRConsentLib$YTV6oHP9kxMujfl6UfAz_oOBEzM.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.sourcepoint.gdpr_cmplibrary.ConsentLibException$NoInternetConnectionException
        at com.sourcepoint.gdpr_cmplibrary.ConsentWebView.loadConsentUIFromUrl(ConsentWebView.java:189)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.lambda$loadConsentUI$4$GDPRConsentLib(GDPRConsentLib.java:301)
        at com.sourcepoint.gdpr_cmplibrary.-$$Lambda$GDPRConsentLib$YTV6oHP9kxMujfl6UfAz_oOBEzM.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-07-07 11:54:37.624 8402-8402/com.sourcepoint.example_app I/**MainActivity: ConsentLibErrorMessage: Error trying to load url to webview: https://notice.sp-prod.net/privacy-manager/index.html?site_id=7639&message_id=122058&consentUUID=8f30f7ec-ce8e-4e8d-b7dd-df76910d914a
```

**Comment by wezley98** [comment]
We are using v5.2.5

**Comment by wezley98** [comment]
<img width="1052" alt="Screenshot 2020-07-07 at 11 14 48" src="https://user-images.githubusercontent.com/1488209/86766944-225bba00-c043-11ea-8d6e-94bd0942bd05.png">

@leodoin Looks like there might on been a change in error handling, between v2 -> v5

We were using this before:

```
 if (consentLibrary.error is ConsentLibException.NoInternetConnectionException) {
            noInternetError = true
        }
```

Should be checking the type on `consentLibrary.cause` instead?

**Comment by wezley98** [comment]
Doing the same but on `Accept` instead of options is slightly different.

<img width="983" alt="Screenshot 2020-07-07 at 11 19 59" src="https://user-images.githubusercontent.com/1488209/86767538-086ea700-c044-11ea-9026-46dd98577110.png">

@leodoin Error has a different type here.

**Comment by leodoin** [comment]
>Should be checking the type on consentLibrary.cause instead?
precisely @wezley98
