### ISSUE TITLE
[ANDROID] No error message when Accept button selected without connection

### ISSUE THREAD

**Issue by wezley98** [SourcePointUSA/android-cmp-app#196]
Issue: **Error Callback is not triggered**

### Steps to Reproduce
- Fresh Install app - CMP Pop up will appear
- Enable airplane mode 
- Select "Accept" button

### Expected
Error message displayed

### Actual
No Error message displayed. It just close the popup

Tested Device :
||Samsung Galaxy S9|10.0

**Comment by leodoin** [comment]
@wezley98, which version of the SDK are you testing with?
I was not able to reproduce from our example app (from master branch). Instead a get the onError callback:
```
2020-07-07 11:43:16.897 7976-7976/com.sourcepoint.example_app E/**MainActivity: Something went wrong: 
    com.sourcepoint.gdpr_cmplibrary.ConsentLibException$NoInternetConnectionException
        at com.sourcepoint.gdpr_cmplibrary.SourcePointClient.sendConsent(SourcePointClient.java:130)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.sendConsent(GDPRConsentLib.java:479)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.onDefaultAction(GDPRConsentLib.java:266)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.onAction(GDPRConsentLib.java:245)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib$1.onAction(GDPRConsentLib.java:218)
        at com.sourcepoint.gdpr_cmplibrary.ConsentWebView$JSReceiverInterface.onAction(ConsentWebView.java:69)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```
Could you make sure to test with our latest release and also try to reproduce on our example app?

**Comment by wezley98** [comment]
We are using v5.2.5

**Comment by wezley98** [comment]
@leodoin Closing this as error looks to be in our app code errorcode is correct from SDK

**Comment by wezley98** [comment]
@leodoin re-opening issue, as issue seems to be when you click `Accept` `setOnConsentUIFinished` is called even when there is no internet` which means we remove the view, then `onError` callback is fired, but it's too late, as view has already been removed so we can't show the error to user.

**Comment by wezley98** [comment]
re-open

**Comment by leodoin** [comment]
@wezley98 , when onError is called the onUIFinished is also called every time. This is the expected behaviour. On your implementation you should wait either for onError/ConsentReady finish the whole flow.
