### ISSUE TITLE
Parsing error causes app crash when using native message

### ISSUE THREAD

**Issue by dpeters-ipc** [SourcePointUSA/android-cmp-app#249]
**Describe the bug**
An invalid response can lead to an app crash

**About your campaign (please complete the following information):**
Demo account:
 "accountId": 22,
 "propertyId": 7094,
 "propertyName": "tcfv2.mobile.demo",
 "pmId": "100699"

**About your environment**
 - SDK version: 5.3.6
 - Device: Pixel 3 XL emulator
 - OS: Android 10

**To Reproduce**
Use the demo account from above and use the native message feature:
buildGDPRConsentLib().run(new NativeMessage(activity));

**Expected behavior**
App does not crash, and error is logged in OnErrorCallback.

**Stacktrace**

2020-08-21 13:06:55.201 11815-11815/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 11815
    java.lang.IllegalArgumentException: Unknown color
        at android.graphics.Color.parseColor(Color.java:1391)
        at com.sourcepoint.gdpr_cmplibrary.NativeMessageAttrs$Style.<init>(NativeMessageAttrs.java:57)
        at com.sourcepoint.gdpr_cmplibrary.NativeMessageAttrs$Attribute.<init>(NativeMessageAttrs.java:41)
        at com.sourcepoint.gdpr_cmplibrary.NativeMessageAttrs.<init>(NativeMessageAttrs.java:26)
        at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.lambda$setNativeMessageView$2$GDPRConsentLib(GDPRConsentLib.java:254)
        at com.sourcepoint.gdpr_cmplibrary.-$$Lambda$GDPRConsentLib$z97h7nKc0UN6caY9AkUeCkdEb0E.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by leodoin** [comment]
Thanks for reporting this @dpeters-ipc . We are on it!

**Comment by leodoin** [comment]
@dpeters-ipc , could you pls give https://github.com/SourcePointUSA/android-cmp-app/releases/tag/5.3.8 a try? :)

**Comment by dpeters-ipc** [comment]
Hi @leodoin , the crash is fixed now. :)

**Comment by leodoin** [comment]
cool 😄
