### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by gnuhel** [SourcePointUSA/android-cmp-app#324]
**Describe the bug**
We are getting SSL error from Sourcepoint Android SDK 5.3.12.

Non-fatal Exception: com.sourcepoint.gdpr_cmplibrary.ConsentLibException: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x789b74f0: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:744 0x68650f10:0x00000000)
       at com.sourcepoint.gdpr_cmplibrary.SourcePointClient$1.onFailure(SourcePointClient.java:83)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

It seems to happen on Android 4.4. Can we habe support for it?

** About your environment **
 - 5.3.12
 - OS: Android 4.4.x

**Comment by hnljp** [comment]
If https://github.com/SourcePointUSA/android-cmp-app/pull/323 is getting merged, are you able to Whitelist the certificates in your OkHttpClient instance.

We have a fallback trust store, if the devices truststore is not accepting the certificate.

**Comment by gnuhel** [comment]
We could fixed it with https://ankushg.com/posts/tls-1.2-on-android/
