### ISSUE TITLE
Crash in  AwDataDirLock.java line 27 org.chromium.android_webview.AwDataDirLock.b 

### ISSUE THREAD

**Issue by dsimetchiev** [SourcePointUSA/android-cmp-app#329]
We get crash reports from Crashlytics in the BILD news and SportBILD apps.
The crash happens mainly on Samsung Galaxy S10, S10+, S10e, Note 10 and Note 10+devices with Android 11.
80 % of the crashes are in the background. A user experiencing the crash will typically get 10 to 20 crashes.
We use thr 5.3.8 version of your SDK.
<img width="1389" alt="Bildschirmfoto 2021-03-17 um 10 30 36" src="https://user-images.githubusercontent.com/38256166/111445709-f6cdbb00-870b-11eb-8ad5-e5bc280cdc8e.png">

Crashlog:
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.netbiscuits.bild.android/de.bild.android.app.splash.SplashActivity}: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.netbiscuits.bild.android (pid 20067), lock owner com.netbiscuits.bild.android (pid 2436)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4864)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
       
       Caused by java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.netbiscuits.bild.android (pid 20067), lock owner com.netbiscuits.bild.android (pid 2436)
       at org.chromium.android_webview.AwDataDirLock.b(AwDataDirLock.java:27)
       at sp0.j(sp0.java:31)
       at sp0.b(sp0.java:22)
       at sp0.l(sp0.java:2)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.g(WebViewChromiumFactoryProvider.java:2)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:14)
       at android.webkit.WebView.<init>(WebView.java:435)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.sourcepoint.gdpr_cmplibrary.ConsentWebView.<init>(ConsentWebView.java:85)
       at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib$1.<init>(GDPRConsentLib.java:200)
       at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.buildWebView(GDPRConsentLib.java:200)
       at com.sourcepoint.gdpr_cmplibrary.GDPRConsentLib.<init>(GDPRConsentLib.java:146)
       at com.sourcepoint.gdpr_cmplibrary.ConsentLibBuilder.getConsentLib(ConsentLibBuilder.java:226)
       at com.sourcepoint.gdpr_cmplibrary.ConsentLibBuilder.build(ConsentLibBuilder.java:205)
       at de.bild.android.cmp.SourcePointDelegator.buildGDPRConsentLib(SourcePointDelegator.java:185)
       at de.bild.android.cmp.SourcePointDelegator.start(SourcePointDelegator.java:66)
       at de.bild.android.cmp.SourcePointConsentManager.start(SourcePointConsentManager.java:30)
       at de.bild.android.app.splash.BildSplashActivity.onResume(BildSplashActivity.java:105)
       at de.bild.android.app.splash.SplashActivity.onResume(SplashActivity.java:109)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
       at android.app.Activity.performResume(Activity.java:8344)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4854)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by andresilveirah** [comment]
Hi @dsimetchiev this seems to be a known issue with the WebView
https://bugs.chromium.org/p/chromium/issues/detail?id=558377

Based on Chrome's dev comment:
> I know this is sucky and I'm sorry but there's not really anything else we can do. WebView 85+ tries to work around it as much as we reasonably can without making apps frequently ANR, but that only reduced the rate of it happening by a couple of percent; it's just too common for the old process to be stuck for way longer than we can realistically wait (i.e. more than the ANR timeout).

I'm not sure we'll be able to solve the issue on our own.

**Comment by dsimetchiev** [comment]
Hi @andresilveirah, thanks to your comment in the thread with the Webview version 89.0.4389.72, I was able to reproduce the crash myself. I was also able to see that the crash does not happen in the newest version 89.0.4389.86.
We will be advising our users to update their Android System Webview version.

**Comment by dsimetchiev** [comment]
I see it was actually not your comment, I just thought it was my screenshot because it looked similar.

**Comment by dsimetchiev** [comment]
Hi @andresilveirah , unfortunately what I was able to reproduce was not this crash, it was a crash caused by a wrong Android System Webview apk. So the crash is still happening for around 1 % of our users with the S10 and Note10 series with Android 11. Could you take a look again. Thanks

**Comment by carmelo-iriti** [comment]
Hi @dsimetchiev ,

are you still experiencing this issue in the new V6 SDK?

**Comment by carmelo-iriti** [comment]
Since I didn’t get any answer, I believe that this issue is not present in the V6
