### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Ljava/util/Base64 – Android 7

### ISSUE THREAD

**Issue by kassim** [SourcePointUSA/android-cmp-app#432]
**Describe the bug**
Receive the following crash stack trace in Crashlytics due to `com.iabtcf.decoder` not being fully compatible below Android 26 due to the lack of  `java.util.Base64` in the SDK

** About your environment **
 - SDK version: 6.2.1
 - Device: Huawei P9, Samsung S6
 - OS: Android 7

**Additional context**

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
       at com.iabtcf.decoder.TCStringDecoder.vectorFromString(TCStringDecoder.java:37)
       at com.iabtcf.decoder.TCStringDecoder.decode(TCStringDecoder.java:57)
       at com.iabtcf.decoder.TCString$-CC.decode(TCString.java:43)
       at com.global.userconsent.repository.CachedConsentRepository.updateConsent(CachedConsentRepository.kt:65)
       at com.global.userconsent.sourcepoint.ConsentLibFactory$LocalClient.onConsentReady(ConsentLibFactory.kt:87)
       at com.sourcepoint.cmplibrary.SpConsentLibImpl$1$1.invoke(SpConsentLibImpl.kt:88)
       at com.sourcepoint.cmplibrary.SpConsentLibImpl$1$1.invoke(SpConsentLibImpl.kt:82)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl.executeOnMain$lambda-0(ExecutorManager.kt:33)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl.$r8$lambda$Pu3LvqGcbtsvgiMpVvWVK4DWqgA(ExecutorManager.kt)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$$ExternalSyntheticLambda1.run()

```

**Comment by carmelo-iriti** [comment]
Hi @kassim,

thanks for the message. The following classes:
       
> at com.iabtcf.decoder.TCStringDecoder.vectorFromString(TCStringDecoder.java:37)
>        at com.iabtcf.decoder.TCStringDecoder.decode(TCStringDecoder.java:57)
>        at com.iabtcf.decoder.TCString$-CC.decode(TCString.java:43)

are not part of our SDK.

**Comment by kassim** [comment]
my apologies, I missed those lines which connect the two
