### ISSUE TITLE
v7.0.0 - Fatal Exception: kotlinx.serialization.SerializationException: Serializer for class 'h' is not found.

### ISSUE THREAD

**Issue by gmorales** [SourcePointUSA/android-cmp-app#566]
We're trying to bump the library from version 6.3.0 to version 7.0.0. But we're facing an isue.

We already have **ProGuard** configured in the project.
````java
# Sourcepoint (CMP)
-keep interface com.sourcepoint.** { *; }
-keep class com.sourcepoint.** { *; }
````

And here is the crash log. This just happens with the **obfuscated** version.
````java
Fatal Exception: kotlinx.serialization.SerializationException: Serializer for class 'h' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
       at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform_commonKt.java:91)
       at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(PlatformKt.java:29)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:60)
       at kotlinx.serialization.SerializersKt.serializer(SerializersKt.java:1)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(SerializersKt__SerializersKt.java:32)
       at com.sourcepoint.cmplibrary.campaign.CampaignManagerImpl.setMessagesOptimizedLocalState(CampaignManager.kt:659)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:203)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:137)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(ExecutorManager.kt:1)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$InternalSyntheticLambda$1$270b46b0f6bf75c77303e1f25d99cf384b0205b066c32f1b52d0c4bc82f1eb7d$0.run(ExecutorManagerImpl.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
````

**Comment by carmelo-iriti** [comment]
Hi @gmorales, 

thanks for the message.

To fix this crash it is enough to add the rules listed in the following [file](https://github.com/Kotlin/kotlinx.serialization/blob/master/rules/common.pro) into the pro-guard  file.

In the next weeks we'll update the readme file with those rules

**Comment by gmorales** [comment]
Thanks @carmelo-iriti! Now it worked :)
