### ISSUE TITLE
ConsentManagerUtilsImpl.updateGdprConsentOptimized  java.lang.ClassNotFoundException - Didn't find class "java.time.format.DateTimeFormatter" on path: 

### ISSUE THREAD

**Issue by HaraldWolz** [SourcePointUSA/android-cmp-app#645]
**Describe the bug**
App crashes on startup on Android 7 devices

**About your campaign (please complete the following information):**

           CampaignsEnv.PUBLIC 
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - 7.0.3
 - Device: Honor 6x, Galaxy J5(2016), Modell:Lenovo TAB4 10 Plus, Modell:Aquaris X5, Galaxy J5(2016)
 -  Android 7 ,7.1.1,  7.1.2

**To Reproduce**
 App crashes on start 

**Expected behavior**
App does not crash

**Screenshots**
not possible

**Additional context**

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl.updateGdprConsentOptimized(ConsentManagerUtils.kt:135)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:167)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:138)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(ExecutorManager.kt)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/oskargmbh.de.oskar-2/base.apk", zip file "/data/app/oskargmbh.de.oskar-2/split_config.armeabi_v7a.apk", zip file "/data/app/oskargmbh.de.oskar-2/split_config.de.apk", zip file "/data/app/oskargmbh.de.oskar-2/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/oskargmbh.de.oskar-2/lib/arm, /data/app/oskargmbh.de.oskar-2/base.apk!/lib/armeabi-v7a, /data/app/oskargmbh.de.oskar-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/oskargmbh.de.oskar-2/split_config.de.apk!/lib/armeabi-v7a, /data/app/oskargmbh.de.oskar-2/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl.updateGdprConsentOptimized(ConsentManagerUtils.kt:135)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:167)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:138)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(ExecutorManager.kt)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by HaraldWolz** [comment]
Hi @andresilveirah,
I tested version 7.0.3 in a Emulator where it seemed to work fine.
After upload in the store I got immediately crashes.
Yesterday I upgraded to suggested version 7.2.2 and uploaded it in the store.
For now I looks fine. 
I am going to close the issue when we are 100% rolled out and the bug does not reapear.

**Comment by andresilveirah** [comment]
Sounds good to me @HaraldWolz , let's keep the issue open until we have the confirmation it's fixed.

**Comment by HaraldWolz** [comment]
@andresilveirah we are now 100% rolled out. 
Looks like it is fixed in 7.2.2
