### ISSUE TITLE
Unexpected JSON token at offset 66 (Parse exception)

### ISSUE THREAD

**Issue by JuanSGarcia** [SourcePointUSA/android-cmp-app#648]
**Describe the bug**
When I run the app in the logcat the parse error appears, and with the repository demo also shows this parse error, when you click on the "Review Consents GPDR" button the app crash.

The error is this: com.sourcepoint.cmplibrary.exception.InvalidApiResponseException: Unexpected JSON token at offset 66: Expected beginning of the string, but got { JSON input: .....PR":{"type": "GDPR", "actions":[{"type": "inline", "js": "var d =.....s

**About your campaign (please complete the following information):**
 - Property Name: "spox.android"
 - Campaign Env: Stage
 - +(CampaignType.GDPR)
 - AuthId (if any)

** About your environment **
 - SDK version: 7.2.2, 7.2.3
 - Device: One Plus 10 Pro, Huawei Mate 20 Pro
 - OS: Android 13, Android 10

**To Reproduce**
1. Run the app or demo, look the logcat
2. Click on button "Review Consents GPDR"  (web-message-demo)
3. App crashes

**Expected behavior**
Show the campaing web message.

**Screenshots**
Exception in Logcat
![image](https://github.com/SourcePointUSA/android-cmp-app/assets/98120746/992de49d-8dc7-41d1-935f-d30555f8b92b)
this screenshot is the GDPR class in MessageApiModel.kt, where actions attribute is declared as a List<String?>?
![image](https://github.com/SourcePointUSA/android-cmp-app/assets/98120746/ec3eaa1e-a4df-4796-99f9-9c958d2fd535)
this screenshot is the JSON response, after the SDK has beeen initialized and loadMessage() function called
![image](https://github.com/SourcePointUSA/android-cmp-app/assets/98120746/58410f11-98a0-4f4e-82fd-5942f6ff17eb)
Crash message:
![image](https://github.com/SourcePointUSA/android-cmp-app/assets/98120746/65192488-d9f8-4105-a10d-4c92006bd4af)

**Additional context**
 com.sourcepoint.cmplibrary.exception.InvalidApiResponseException: Unexpected JSON token at offset 66: Expected beginning of the string, but got {
JSON input: .....PR":{"type":"GDPR","actions":[{"type":"inline","js":"var d =.....
    at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.toConsentLibException(FunctionalUtils.kt:40)
    at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.check(FunctionalUtils.kt:33)
    at com.sourcepoint.cmplibrary.data.network.converter.JsonConverterImpl.toMessagesResp(JsonConverterImpl.kt:107)
    at com.sourcepoint.cmplibrary.data.network.util.ResponseManagerImpl.parseMessagesResp(ResponseManagerImpl.kt:252)
    at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl$getMessages$1.invoke(NetworkClientImpl.kt:143)
    at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl$getMessages$1.invoke(NetworkClientImpl.kt:126)
    at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.check(FunctionalUtils.kt:30)
    at com.sourcepoint.cmplibrary.data.network.NetworkClientImpl.getMessages(NetworkClientImpl.kt:126)
    at com.sourcepoint.cmplibrary.data.ServiceImpl.getMessages(Unknown Source:7)
    at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:189)
    at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:127)
    at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
    at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(Unknown Source:0)
    at com.sourcepoint.cmplibrary.core.-$$Lambda$ExecutorManagerImpl$executeOnWorkerThread$1$YcU9LB-LQlcZOnRwBNhL6k0AYg0.run(Unknown Source:2)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 66: Expected beginning of the string, but got {
JSON input: .....PR":{"type":"GDPR","actions":[{"type":"inline","js":"var d =.....
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
    at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:514)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:513)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeStringLenient(AbstractJsonLexer.kt:390)
    at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeStringLenientNotNull(AbstractJsonLexer.kt:362)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:241)
    at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:142)
    at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:138)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
    at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
    at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
    at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.GDPR$$serializer.deserialize(MessagesApiModel.kt:116)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.GDPR$$serializer.deserialize(MessagesApiModel.kt:116)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.Campaigns$$serializer.deserialize(MessagesApiModel.kt:85)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.Campaigns$$serializer.deserialize(MessagesApiModel.kt:85)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.MessagesResp$$serializer.deserialize(MessagesApiModel.kt:33)
    at com.sourcepoint.cmplibrary.data.network.model.optimized.MessagesResp$$serializer.deserialize(MessagesApiModel.kt:33)
    at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
    at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
    at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
    at com.sourcepoint.cmplibrary.data.network.converter.JsonConverterImpl$toMessagesResp$1.invoke(JsonConverterImpl.kt:120)
    at com.sourcepoint.cmplibrary.data.network.converter.JsonConverterImpl$toMessagesResp$1.invoke(JsonConverterImpl.kt:107)
    at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.check(FunctionalUtils.kt:30)

**Comment by andresilveirah** [comment]
Hi @JuanSGarcia thank you for reporting this issue and sorry for the delayed response. The latest SDK release `v7.2.5` addresses this issue. Can you give it a try and let me know if the problem persists for you?
