### ISSUE TITLE
InvalidConsentResponse is thrown since yesterday

### ISSUE THREAD

**Issue by kasim-canol-sz** [SourcePointUSA/android-cmp-app#727]
**Describe the bug**
Since yesterday our users can't save any consents anymore. As a result, the consent screen is shown on every app-start.
We didn't do any code changes. It seems like the issue is also occuring on previous SDK versions.

**About your environment**
 - SDK version: 7.4.1
 - Device: Any
 - OS: Android

**To Reproduce**
1. Start the app

**Expected behavior**
Once successfully saved, the consent screen shouldn't re-appear on app-start.

**Screenshots**
<img width="1375" alt="image" src="https://github.com/SourcePointUSA/android-cmp-app/assets/143796930/11318604-9e52-4280-aec5-8624e47405da">

**Additional context**
Exception:
```
Sourcepoint error occurred
com.sourcepoint.cmplibrary.exception.InvalidConsentResponse: The GDPR consent object cannot be null!!!
	at com.sourcepoint.cmplibrary.data.ServiceImpl$sendConsentGdpr$1.invoke(ServiceImpl.kt:415)
	at com.sourcepoint.cmplibrary.data.ServiceImpl$sendConsentGdpr$1.invoke(ServiceImpl.kt:338)
	at com.sourcepoint.cmplibrary.util.FunctionalUtilsKt.check(FunctionalUtils.kt:21)
	at com.sourcepoint.cmplibrary.data.ServiceImpl.sendConsentGdpr(ServiceImpl.kt:338)
	at com.sourcepoint.cmplibrary.data.ServiceImpl.sendConsent(ServiceImpl.kt:318)
	at com.sourcepoint.cmplibrary.consent.ConsentManagerImpl$sendConsent$1.invoke(ConsentManager.kt:113)
	at com.sourcepoint.cmplibrary.consent.ConsentManagerImpl$sendConsent$1.invoke(ConsentManager.kt:112)
	at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnSingleThread$1.invoke$lambda-0(ExecutorManager.kt:46)
	at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnSingleThread$1.$r8$lambda$9nf0hQbH6sUNFwBgbyjBBNAEVFY(Unknown Source:0)
	at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnSingleThread$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by carmelo-iriti** [comment]
Hi @kasim-canol-sz ,

Thanks for the message,

can you please send your configuration object on carmelo@sourcepoint.com?

**Comment by kasim-canol-sz** [comment]
Hi @carmelo-iriti, done.

**Comment by kasim-canol-sz** [comment]
@carmelo-iriti This issue is also occuring on our current store-app, which uses Sourcepoint library version **_7.2.8_**

It seems like it could be a backend issue because this behaviour is occuring accross library version from **_7.2.8_** to **_7.4.1_**

**Comment by kasim-canol-sz** [comment]
After a long investigation we found out that one of our vendors is not granting the consent. As a full-consent is elementary for our users without a subscription, we revoke the subscription on our side and trigger a new consent. Therefore we run into a loop. We can close this issue, as there's no TODO on your side. 

@carmelo-iriti Thank you for your support!
